``Chapter 2 -- Vectors, Matrices, and Multidimensional Arrays``

In [2]:
import numpy as np

In [3]:
#help(np.ndarray)

In [4]:
data = np.array([[1,2], [3,4], [5,6]])

In [5]:
type(data)

numpy.ndarray

In [6]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
data.ndim

2

In [8]:
data.shape

(3, 2)

In [9]:
data.size

6

In [10]:
data.dtype

dtype('int64')

In [11]:
data.nbytes

48

In [12]:
len(data)

3

In [13]:
sth = data.shape
sth[0]

3

In [14]:
help(len) # or "len?"

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [15]:
data.shape[0]

3

In [16]:
#help(np.dtype)

In [17]:
np.array([1, 2, 3], dtype=np.int) # good to specify datatype

array([1, 2, 3])

In [18]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [19]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [20]:
# Type casting

data = np.array([1,2,3], dtype=np.float)

In [21]:
data

array([1., 2., 3.])

In [22]:
data.dtype

dtype('float64')

In [23]:
data = np.array(data,dtype=np.int)

In [24]:
data

array([1, 2, 3])

In [25]:
data.dtype

dtype('int64')

In [26]:
data = np.array([1,2,3], dtype=complex)

In [27]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
data.dtype

dtype('complex128')

In [29]:
data.astype(np.float)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [30]:
data.astype(np.int)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 2, 3])

In [31]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [32]:
data = data.astype(np.float)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


In [33]:
data

array([1., 2., 3.])

In [34]:
d1 = np.array([1,2,3], dtype=np.float)
d2 = np.array([1,2,3], dtype=np.complex)

In [35]:
d1+d2 # float+complex --> complex

array([2.+0.j, 4.+0.j, 6.+0.j])

In [36]:
# Always set the data type of the array. The default is float.

np.sqrt(np.array([-1,0,1])) # Warning. Maybe an error in some application

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.])

In [37]:
np.sqrt(np.array([-1,0,1], dtype=np.complex)) # No warning. No error.

array([0.+1.j, 0.+0.j, 1.+0.j])

In [38]:
# Extracting real and imaginary parts of the array

data = np.array([1,2,3], dtype=np.complex)

In [39]:
data.real

array([1., 2., 3.])

In [40]:
data.imag

array([0., 0., 0.])

In [41]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [42]:
data.ndim

1

In [43]:
data.shape

(3,)

In [44]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [45]:
np.array([[1,2],[3,4]]).ndim

2

In [46]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [47]:
# Arrays filled with constant values

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones(5, dtype=np.complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [50]:
2.3*np.ones(10)

array([2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3])

In [51]:
np.full(10,4.2)

array([4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2])

In [52]:
ary = np.empty(6)
ary

array([7.69165785e+218, 1.35617292e+248, 3.36679258e-057, 5.02908831e-037,
       2.57071600e+184, 6.37344683e-322])

In [53]:
ary = ary.fill(3.0)
ary

In [54]:
# Incremental sequence arrays

np.arange(0,10,1.5,dtype=np.float)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [55]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [56]:
# mesh-grid arrays

x = np.array([-1,0,1])
y = np.array([-2,0,2])
X,Y = np.meshgrid(x,y)

In [57]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [58]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [59]:
Z = (X+Y)**2

In [60]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [61]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

In [62]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

In [63]:
# Creating Arrays with Properties of Other Arrays.

def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y
# y is created using 'np.ones_like', which results in an array of the same size and data type as x, and filled with ones.

Creating Matrix Arrays.

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.eye(6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [66]:
np.eye(6, k=-3)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [67]:
np.diag(np.arange(0,20,5), k=0)

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

Indexing and Slicing

In [69]:
a = np.arange(0,11)

In [70]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a.shape

(11,)

In [74]:
a[10]

10

In [75]:
a[-1]

10

In [76]:
a[0]

0

In [77]:
a[4]

4

In [78]:
a[2:5]

array([2, 3, 4])

In [79]:
a[2:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
a[2:-0]

array([], dtype=int64)

In [82]:
a[2:0]

array([], dtype=int64)

In [83]:
a[2:8:2]

array([2, 4, 6])

In [84]:
a[3:6]

array([3, 4, 5])

In [85]:
a[:4]

array([0, 1, 2, 3])

In [86]:
a[-3:]

array([ 8,  9, 10])

In [87]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [88]:
# Reverse the array and select only the every 3rd value.
a[::-3]

array([10,  7,  4,  1])

Multidimensional Arrays

In [89]:
f = lambda m,n: n+10*m

In [90]:
A = np.fromfunction(f,(6,6), dtype=int)

In [91]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [95]:
A.ndim

2

In [96]:
A.shape

(6, 6)

In [97]:
A[:1]

array([[0, 1, 2, 3, 4, 5]])

In [100]:
A[:,1] # The second column only.

array([ 1, 11, 21, 31, 41, 51])

In [101]:
A[1,:] # The second row only.

array([10, 11, 12, 13, 14, 15])

In [102]:
A[0,:]

array([0, 1, 2, 3, 4, 5])

In [103]:
A[:3,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [104]:
A[:4,:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [105]:
A[4:,4:]

array([[44, 45],
       [54, 55]])

In [106]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [107]:
A[3:,3:]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [108]:
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [109]:
A[::-2,::-2]

array([[55, 53, 51],
       [35, 33, 31],
       [15, 13, 11]])

In [110]:
A[1::2,1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

Views

In [111]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [112]:
B = A[1:4,1:3]

In [113]:
B

array([[11, 12],
       [21, 22],
       [31, 32]])

In [114]:
B[:,:] = 0

In [115]:
B

array([[0, 0],
       [0, 0],
       [0, 0]])

In [116]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0, 13, 14, 15],
       [20,  0,  0, 23, 24, 25],
       [30,  0,  0, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [125]:
C = A[1:,:-2].copy()

In [126]:
C

array([[10,  0,  0, 13],
       [20,  0,  0, 23],
       [30,  0,  0, 33],
       [40, 41, 42, 43],
       [50, 51, 52, 53]])

In [127]:
C[:,:] = 0

In [128]:
C

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [129]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0, 13, 14, 15],
       [20,  0,  0, 23, 24, 25],
       [30,  0,  0, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

Fancy Indexing and Boolean-valued Indexing

In [3]:
A = np.linspace(0,1,11)

In [4]:
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [5]:
A[np.array([0,2,4])]

array([0. , 0.2, 0.4])

In [7]:
A[[0,6,3]]

array([0. , 0.6, 0.3])

In [8]:
A<0.5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [11]:
A[(A<0.4)&(A>0.7)]

array([], dtype=float64)

In [12]:
A[A<0.4]

array([0. , 0.1, 0.2, 0.3])

In [13]:
A = np.arange(10)

In [14]:
indices = [3,5,6]

In [15]:
B = A[indices]

In [16]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
B

array([3, 5, 6])

In [18]:
data = np.array([[1,2],[3,4]])

In [19]:
data

array([[1, 2],
       [3, 4]])

In [20]:
data.reshape(1,4)

array([[1, 2, 3, 4]])

In [21]:
data.ndim

2

In [23]:
data.reshape(4)

array([1, 2, 3, 4])

In [24]:
data.ndim

2

In [25]:
data

array([[1, 2],
       [3, 4]])

In [28]:
data1 = data.reshape(1,4)

In [29]:
data1

array([[1, 2, 3, 4]])

In [30]:
data1.ndim

2

In [31]:
data2 = data.reshape(4)

In [32]:
data2

array([1, 2, 3, 4])

In [33]:
data2.ndim

1

In [34]:
data

array([[1, 2],
       [3, 4]])

In [35]:
data3 = data.flatten()

In [36]:
data3

array([1, 2, 3, 4])

In [39]:
column = data3[:,np.newaxis]

In [40]:
column

array([[1],
       [2],
       [3],
       [4]])

In [41]:
row = data3[np.newaxis,:]

In [42]:
row

array([[1, 2, 3, 4]])

In [43]:
data3

array([1, 2, 3, 4])

In [44]:
column1 = np.expand_dims(data3, axis=1)

In [45]:
column1

array([[1],
       [2],
       [3],
       [4]])

In [47]:
row1 = np.expand_dims(data3, axis=0)

In [48]:
row1

array([[1, 2, 3, 4]])

In [49]:
column1.shape

(4, 1)

In [50]:
row1.shape

(1, 4)

In [54]:
np.vstack((row1,row1,row1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [55]:
np.hstack((column1,column1,column1))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

Vectorized Expressions

Arthmetic Operations

In [56]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [57]:
x+y

array([[ 6,  8],
       [10, 12]])

In [58]:
y-x

array([[4, 4],
       [4, 4]])

In [59]:
x*y

array([[ 5, 12],
       [21, 32]])

In [60]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [61]:
x*2

array([[2, 4],
       [6, 8]])

In [62]:
x.shape

(2, 2)

In [64]:
z = np.array([[2,4]])

In [65]:
z.shape

(1, 2)

In [66]:
x/z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [67]:
zz = np.concatenate([z,z],axis=0)
zz

array([[2, 4],
       [2, 4]])

In [68]:
x/zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [69]:
z = np.array([[2],[4]])

In [70]:
z.shape

(2, 1)

In [71]:
x.shape

(2, 2)

In [72]:
x/z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [73]:
zz = np.concatenate([z,z],axis=1)
zz

array([[2, 2],
       [4, 4]])

In [74]:
x

array([[1, 2],
       [3, 4]])

In [75]:
x/zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

Elementwise Functions

In [76]:
x = np.linspace(-1,1,11)

In [77]:
np.add(np.sin(x)**2,np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
def heaviside(x):
    return 1 if x>0 else 0

In [79]:
heaviside(1)

1

In [80]:
heaviside(-2.5)

0

In [81]:
heaviside(30)

1

In [82]:
x = np.linspace(-5,5,10)

In [83]:
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
heaviside = np.vectorize(heaviside)

In [87]:
heaviside(x) # great but slow

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [91]:
def heaviside2(x):
    return 1.0*(x>0)

In [92]:
heaviside2(30)

1.0

In [93]:
heaviside2(x)

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

Aggregate Functions

In [94]:
data = np.random.normal(size=(15,15))

In [96]:
data.mean()

-0.0672536624893777

In [97]:
np.mean(data)

-0.0672536624893777

In [98]:
data = np.random.normal(size=(5,10,15))

In [100]:
data.ndim

3

In [101]:
data.shape

(5, 10, 15)

In [102]:
data.sum(axis=0).shape

(10, 15)

In [104]:
data.sum(axis=1).shape

(5, 15)

In [105]:
data.sum(axis=(0,2)).shape

(10,)

In [106]:
data.sum()

-29.969231075035324

Boolean Arrays and Conditional Expressions

In [107]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a<b

array([ True,  True, False, False])

In [108]:
(a<b).dtype

dtype('bool')

In [109]:
np.all(a<b)

False

In [110]:
np.any(a<b)

True

In [111]:
if np.all(a<b):
    print("All elements in a are smaller than their corresponding elements in b")
elif np.any(a<b):
    print("Some elements in a are smaller than their corresponding elements in b")
else:
    print("All elements in b are smaller than their corresponding elements in a")

Some elements in a are smaller than their corresponding elements in b


In [112]:
x = np.array([-2,-1,0,1,2])
x>0

array([False, False, False,  True,  True])

In [113]:
1*(x>0)

array([0, 0, 0, 1, 1])

In [114]:
x = np.linspace(-4,4,9)

In [115]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [116]:
np.where(x<0,x**2,x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [117]:
np.select([x<-1,x<2,x>=2],[x**2,x**3,x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [118]:
np.choose([0,0,0,1,1,1,2,2,2],[x,x**2,x+2])

array([-4., -3., -2.,  1.,  0.,  1.,  4.,  5.,  6.])

In [123]:
np.choose([2,0,0,1,1,0,2,1,2],[x+1,x+2,x+3])

array([-1., -2., -1.,  1.,  2.,  2.,  5.,  5.,  7.])

In [124]:
np.nonzero(abs(x)>2)

(array([0, 1, 7, 8]),)

In [125]:
abs(x)

array([4., 3., 2., 1., 0., 1., 2., 3., 4.])

In [126]:
abs(x)>2

array([ True,  True, False, False, False, False, False,  True,  True])

In [127]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [128]:
np.nonzero(x)

(array([0, 1, 2, 3, 5, 6, 7, 8]),)

In [129]:
np.nonzero(abs(x)>2)

(array([0, 1, 7, 8]),)

In [130]:
x[np.nonzero(abs(x)>2)]

array([-4., -3.,  3.,  4.])

In [131]:
x[abs(x)>2]

array([-4., -3.,  3.,  4.])

Set Operations

In [132]:
a = np.unique([1,2,3,3])
b = np.unique([2,3,4,4,5,6,5])

In [133]:
a

array([1, 2, 3])

In [134]:
b

array([2, 3, 4, 5, 6])

In [135]:
np.in1d(a,b)

array([False,  True,  True])

In [136]:
1 in a

True

In [137]:
1 in b

False

In [138]:
np.all(np.in1d(a,b))

False

In [139]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [140]:
np.intersect1d(a,b)

array([2, 3])

In [141]:
np.setdiff1d(a,b)

array([1])

In [142]:
np.setdiff1d(b,a)

array([4, 5, 6])

Operations on Arrays

In [143]:
data = np.arange(9).reshape(3,3)

In [144]:
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [146]:
data = np.random.randn(1,2,3,4,5)

In [148]:
data.ndim

5

In [149]:
data.shape

(1, 2, 3, 4, 5)

In [150]:
data.T.shape

(5, 4, 3, 2, 1)

In [155]:
dat = np.linspace(1,10,9).reshape(3,3)

In [156]:
dat

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [159]:
np.fliplr(dat)

array([[ 3.25 ,  2.125,  1.   ],
       [ 6.625,  5.5  ,  4.375],
       [10.   ,  8.875,  7.75 ]])

In [160]:
np.flipud(dat)

array([[ 7.75 ,  8.875, 10.   ],
       [ 4.375,  5.5  ,  6.625],
       [ 1.   ,  2.125,  3.25 ]])

In [161]:
dat.T

array([[ 1.   ,  4.375,  7.75 ],
       [ 2.125,  5.5  ,  8.875],
       [ 3.25 ,  6.625, 10.   ]])

In [162]:
np.rot90(dat)

array([[ 3.25 ,  6.625, 10.   ],
       [ 2.125,  5.5  ,  8.875],
       [ 1.   ,  4.375,  7.75 ]])

In [164]:
np.sort(dat,axis=0)

array([[ 1.   ,  2.125,  3.25 ],
       [ 4.375,  5.5  ,  6.625],
       [ 7.75 ,  8.875, 10.   ]])

In [165]:
A = np.arange(1,7).reshape(2,3)

In [166]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
B = np.arange(1,7).reshape(3,2)

In [168]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [169]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [170]:
np.dot(B,A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [174]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [175]:
x = np.arange(3)
x

array([0, 1, 2])

In [176]:
np.dot(A,x)

array([ 5, 14, 23])

In [177]:
A.dot(x)

array([ 5, 14, 23])

In [178]:
x.dot(A)

array([15, 18, 21])

In [180]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Ap = np.dot(B,np.dot(A,np.linalg.inv(B)))
Ap

array([[-0.97436879,  0.51717178,  0.94389575],
       [-0.41079594,  0.64980349,  1.36875383],
       [-1.75319891,  0.62111903,  2.26745866]])

In [181]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[-0.97436879,  0.51717178,  0.94389575],
       [-0.41079594,  0.64980349,  1.36875383],
       [-1.75319891,  0.62111903,  2.26745866]])

In [182]:
Ap = B@A@np.linalg.inv(B)
Ap

array([[-0.97436879,  0.51717178,  0.94389575],
       [-0.41079594,  0.64980349,  1.36875383],
       [-1.75319891,  0.62111903,  2.26745866]])

In [184]:
A = np.matrix(A)
B = np.matrix(B)
Ap = B*A*B.I
Ap

matrix([[-0.97436879,  0.51717178,  0.94389575],
        [-0.41079594,  0.64980349,  1.36875383],
        [-1.75319891,  0.62111903,  2.26745866]])

In [185]:
A = np.asmatrix(A)
B = np.asmatrix(B)
Ap = B*A*B.I
Ap = np.asarray(Ap)
Ap

array([[-0.97436879,  0.51717178,  0.94389575],
       [-0.41079594,  0.64980349,  1.36875383],
       [-1.75319891,  0.62111903,  2.26745866]])

In [186]:
np.inner(x,x)

5

In [187]:
np.dot(x,x)

5

In [188]:
y = x[:,np.newaxis]
y

array([[0],
       [1],
       [2]])

In [189]:
y.T.dot(y)

array([[5]])

In [190]:
np.dot(y.T,y)

array([[5]])

In [191]:
x = np.array([1,2,3])
np.outer(x,x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [192]:
np.outer(np.array([1,2,3,4]),np.array([1,2,3,4]))

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [193]:
np.kron(x,x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [194]:
np.kron(np.array([1,2,3,4]),np.array([1,2,3,4]))

array([ 1,  2,  3,  4,  2,  4,  6,  8,  3,  6,  9, 12,  4,  8, 12, 16])

In [196]:
np.kron(x[:,np.newaxis],x[np.newaxis,:])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [197]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
np.einsum("n,n",x,y)

70

In [198]:
np.inner(x,y)

70