``Chapter 2 -- Vectors, Matrices, and Multidimensional Arrays``

In [2]:
import numpy as np

In [3]:
#help(np.ndarray)

In [4]:
data = np.array([[1,2], [3,4], [5,6]])

In [5]:
type(data)

numpy.ndarray

In [6]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
data.ndim

2

In [8]:
data.shape

(3, 2)

In [9]:
data.size

6

In [10]:
data.dtype

dtype('int64')

In [11]:
data.nbytes

48

In [12]:
len(data)

3

In [13]:
sth = data.shape
sth[0]

3

In [14]:
help(len) # or "len?"

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [15]:
data.shape[0]

3

In [16]:
#help(np.dtype)

In [17]:
np.array([1, 2, 3], dtype=np.int) # good to specify datatype

array([1, 2, 3])

In [18]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [19]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [20]:
# Type casting

data = np.array([1,2,3], dtype=np.float)

In [21]:
data

array([1., 2., 3.])

In [22]:
data.dtype

dtype('float64')

In [23]:
data = np.array(data,dtype=np.int)

In [24]:
data

array([1, 2, 3])

In [25]:
data.dtype

dtype('int64')

In [26]:
data = np.array([1,2,3], dtype=complex)

In [27]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
data.dtype

dtype('complex128')

In [29]:
data.astype(np.float)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1., 2., 3.])

In [30]:
data.astype(np.int)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 2, 3])

In [31]:
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [32]:
data = data.astype(np.float)

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


In [33]:
data

array([1., 2., 3.])

In [34]:
d1 = np.array([1,2,3], dtype=np.float)
d2 = np.array([1,2,3], dtype=np.complex)

In [35]:
d1+d2 # float+complex --> complex

array([2.+0.j, 4.+0.j, 6.+0.j])

In [36]:
# Always set the data type of the array. The default is float.

np.sqrt(np.array([-1,0,1])) # Warning. Maybe an error in some application

/home/sam/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.])

In [37]:
np.sqrt(np.array([-1,0,1], dtype=np.complex)) # No warning. No error.

array([0.+1.j, 0.+0.j, 1.+0.j])

In [38]:
# Extracting real and imaginary parts of the array

data = np.array([1,2,3], dtype=np.complex)

In [39]:
data.real

array([1., 2., 3.])

In [40]:
data.imag

array([0., 0., 0.])

In [41]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [42]:
data.ndim

1

In [43]:
data.shape

(3,)

In [44]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [45]:
np.array([[1,2],[3,4]]).ndim

2

In [46]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [47]:
# Arrays filled with constant values

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones(5, dtype=np.complex)

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [50]:
2.3*np.ones(10)

array([2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3])

In [51]:
np.full(10,4.2)

array([4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2])

In [52]:
ary = np.empty(6)
ary

array([7.69165785e+218, 1.35617292e+248, 3.36679258e-057, 5.02908831e-037,
       2.57071600e+184, 6.37344683e-322])

In [53]:
ary = ary.fill(3.0)
ary

In [54]:
# Incremental sequence arrays

np.arange(0,10,1.5,dtype=np.float)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [55]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [56]:
# mesh-grid arrays

x = np.array([-1,0,1])
y = np.array([-2,0,2])
X,Y = np.meshgrid(x,y)

In [57]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [58]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [59]:
Z = (X+Y)**2

In [60]:
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [61]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

In [62]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

In [63]:
# Creating Arrays with Properties of Other Arrays.

def f(x):
    y = np.ones_like(x)
    # compute with x and y
    return y
# y is created using 'np.ones_like', which results in an array of the same size and data type as x, and filled with ones.

Creating Matrix Arrays.

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
np.eye(6, k=2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [66]:
np.eye(6, k=-3)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [67]:
np.diag(np.arange(0,20,5), k=0)

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

Indexing and Slicing

In [69]:
a = np.arange(0,11)

In [70]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a.shape

(11,)

In [74]:
a[10]

10

In [75]:
a[-1]

10

In [76]:
a[0]

0

In [77]:
a[4]

4

In [78]:
a[2:5]

array([2, 3, 4])

In [79]:
a[2:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
a[2:-0]

array([], dtype=int64)

In [82]:
a[2:0]

array([], dtype=int64)

In [83]:
a[2:8:2]

array([2, 4, 6])

In [84]:
a[3:6]

array([3, 4, 5])

In [85]:
a[:4]

array([0, 1, 2, 3])

In [86]:
a[-3:]

array([ 8,  9, 10])

In [87]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [88]:
# Reverse the array and select only the every 3rd value.
a[::-3]

array([10,  7,  4,  1])

Multidimensional Arrays

In [89]:
f = lambda m,n: n+10*m

In [90]:
A = np.fromfunction(f,(6,6), dtype=int)

In [91]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [95]:
A.ndim

2

In [96]:
A.shape

(6, 6)

In [97]:
A[:1]

array([[0, 1, 2, 3, 4, 5]])

In [100]:
A[:,1] # The second column only.

array([ 1, 11, 21, 31, 41, 51])

In [101]:
A[1,:] # The second row only.

array([10, 11, 12, 13, 14, 15])

In [102]:
A[0,:]

array([0, 1, 2, 3, 4, 5])

In [103]:
A[:3,:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [104]:
A[:4,:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [105]:
A[4:,4:]

array([[44, 45],
       [54, 55]])

In [106]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [107]:
A[3:,3:]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [108]:
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [109]:
A[::-2,::-2]

array([[55, 53, 51],
       [35, 33, 31],
       [15, 13, 11]])

In [110]:
A[1::2,1::3]

array([[11, 14],
       [31, 34],
       [51, 54]])

Views